export const recent_projects = [
  {
    title: "Ongoing Barangay Information System",
    desc: "A web-based Barangay Information System used for managing resident records, document requests, announcements, and community activities. It includes a Community Hub feature where residents can view updates, events, and notices from the barangay. The system helps organize information and makes daily barangay processes easier to manage.",
    tools: [
      "JavaScript",
      "React",
      "Tailwind",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Github",
      "Git",
      "Shadcn ui",
      "REST",
      "MVC",
      "PostMan",
      "Resend API",
      "Third-Party API'S",
    ],
  },
  {
    title: "Booking Management for Jenriva Resort Web Base",
    desc: "Helps managing reservations with advance data analytics, email notifications and helps accessible booking for customers",
    tools: [
      "JavaScript",
      "React",
      "Tailwind",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Github",
      "Git",
      "Shadcn ui",
      "REST",
      "MVC",
      "PostMan",
      "Resend API",
    ],
  },
  {
    title: "Online Booking for Jenariva Resort Mobile Base",
    desc: "Integrated of the web version for customer purpose",
    tools: ["Java", "Kotlin", "Github", "Git", "PostMan"],
  },
  {
    title: "Online Reservation System for Casa Pricilla Resort",
    desc: "Helps managing reservations and accessible booking",
    tools: ["PHP", "JavaScript", "MySQL", "CSS", "HTML", "PostMan"],
  },
  {
    title: "ByteManga",
    desc: "Online Wiki for Manga and Anime",
    tools: [ "JavaScript","React", "Node.js", "Tailwind CSS","PostMan", "Jikan API"],
  },
  {
    title: "Crypto Explorer",
    desc: "Simple project for exploring crypto exchange rates",
    tools: ["JavaScript", "React", "Tailwind CSS", "Node.js", "CoinGecko API"],
  },
   {
    title: "Flash Me",
    desc: "Simple PhotoBooth website",
    tools: ["JavaScript", "React", "Tailwind CSS"],
  },
];
